# Generated by Django 4.1.3 on 2022-11-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.FilePathField(default=None, path='static/main_app'),
        ),
    ]
