# Generated by Django 4.1.3 on 2022-11-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
    ]
