# Generated by Django 4.1.3 on 2022-11-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_character_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('img_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-date']},
        ),
    ]
