# Generated by Django 4.1.3 on 2022-11-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_award_alter_token_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='color',
        ),
    ]
