# Generated by Django 4.1.3 on 2022-11-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_character_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_path',
            field=models.CharField(default='https://i.imgur.com/OeHqYtR.png', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='img_path',
            field=models.CharField(max_length=200),
        ),
    ]
